// src/EventsList.svelte
<script lang="ts">
  import { untrack } from "svelte";
  import { SvelteSet } from "svelte/reactivity";
  import type { SessionEvent } from "./types";
  import { groupEventsByIteration } from "./iteration-groups";
  import { eventEmoji, eventLabel } from "./event-format";
  import IterationGroup from "./IterationGroup.svelte";

  let { events, isLive = false }: { events: SessionEvent[]; isLive?: boolean } =
    $props();

  let eventsContainer: HTMLElement | undefined = $state();
  let autoScroll = $state(true);
  let expandedEvents = new SvelteSet<number>();
  let expandedIterations = new SvelteSet<number>();

  let grouped = $derived(groupEventsByIteration(events));

  // Compute a mapping: for each iteration group, what is its starting global index in the flat events array.
  // standalone "before" events come first, then iteration groups in order, then standalone "after" events.
  let iterationGlobalStartIndices = $derived.by(() => {
    // eslint-disable-next-line svelte/prefer-svelte-reactivity -- local computation, not reactive state
    const indices = new Map<number, number>();
    let offset = 0;
    // Count "before" standalone events
    for (const s of grouped.standaloneEvents) {
      if (s.index === "before") offset++;
    }
    for (const iter of grouped.iterations) {
      indices.set(iter.iteration, offset);
      offset += iter.events.length;
    }
    return indices;
  });

  let afterStartIndex = $derived.by(() => {
    let offset = 0;
    for (const s of grouped.standaloneEvents) {
      if (s.index === "before") offset++;
    }
    for (const iter of grouped.iterations) {
      offset += iter.events.length;
    }
    return offset;
  });

  let lastExpandedIter = $state(-1);

  $effect(() => {
    if (isLive && grouped.iterations.length > 0) {
      const lastIter =
        grouped.iterations[grouped.iterations.length - 1].iteration;
      if (lastIter !== lastExpandedIter) {
        lastExpandedIter = lastIter;
        expandedIterations.add(lastIter);
      }
    }
  });

  function toggleIteration(iteration: number) {
    if (expandedIterations.has(iteration)) expandedIterations.delete(iteration);
    else expandedIterations.add(iteration);
  }

  function toggleEvent(globalIndex: number) {
    if (expandedEvents.has(globalIndex)) expandedEvents.delete(globalIndex);
    else expandedEvents.add(globalIndex);
  }

  function formatTime(ts?: number): string {
    if (!ts) return "";
    const d = new Date(ts);
    return d.toLocaleTimeString([], {
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });
  }

  function handleEventsScroll() {
    if (!eventsContainer) return;
    const { scrollTop, scrollHeight, clientHeight } = eventsContainer;
    autoScroll = scrollHeight - scrollTop - clientHeight < 40;
  }

  function jumpToBottom() {
    eventsContainer?.scrollTo({
      top: eventsContainer.scrollHeight,
      behavior: "smooth",
    });
    autoScroll = true;
  }

  $effect(() => {
    if (events.length > 0 && untrack(() => autoScroll)) {
      requestAnimationFrame(() => {
        eventsContainer?.scrollTo({
          top: eventsContainer.scrollHeight,
          behavior: "smooth",
        });
      });
    }
  });
</script>

{#if events.length > 0}
  <section class="events">
    <div class="events-header">
      <h2>Events</h2>
      <span class="event-count">{events.length}</span>
    </div>
    <div
      class="events-scroll"
      bind:this={eventsContainer}
      onscroll={handleEventsScroll}
    >
      <ul>
        {#each grouped.standaloneEvents.filter((s) => s.index === "before") as standalone, i (i)}
          <li
            class="event {standalone.event.kind}"
            class:expanded={expandedEvents.has(i)}
          >
            <button class="event-btn" onclick={() => toggleEvent(i)}>
              <span class="event-emoji"
                >{eventEmoji(standalone.event.kind)}</span
              >
              <span class="event-text">{eventLabel(standalone.event)}</span>
              <span class="event-time">{formatTime(standalone.event._ts)}</span>
            </button>
            {#if expandedEvents.has(i) && standalone.event.kind === "git_sync_failed" && standalone.event.error}
              <pre class="tool-input-detail">{standalone.event.error}</pre>
            {/if}
          </li>
        {/each}

        {#each grouped.iterations as iter (iter.iteration)}
          <IterationGroup
            group={iter}
            expanded={expandedIterations.has(iter.iteration)}
            onToggle={() => toggleIteration(iter.iteration)}
            {formatTime}
            {expandedEvents}
            {toggleEvent}
            globalStartIndex={iterationGlobalStartIndices.get(iter.iteration) ??
              0}
          />
        {/each}

        {#each grouped.standaloneEvents.filter((s) => s.index === "after") as standalone, i (i)}
          {@const globalIndex = afterStartIndex + i}
          <li
            class="event {standalone.event.kind}"
            class:expanded={expandedEvents.has(globalIndex)}
          >
            <button class="event-btn" onclick={() => toggleEvent(globalIndex)}>
              <span class="event-emoji"
                >{eventEmoji(standalone.event.kind)}</span
              >
              <span class="event-text">{eventLabel(standalone.event)}</span>
              <span class="event-time">{formatTime(standalone.event._ts)}</span>
            </button>
            {#if expandedEvents.has(globalIndex) && standalone.event.kind === "git_sync_failed" && standalone.event.error}
              <pre class="tool-input-detail">{standalone.event.error}</pre>
            {/if}
          </li>
        {/each}
      </ul>
    </div>
    {#if !autoScroll}
      <button class="jump-bottom" onclick={jumpToBottom}>↓ New events</button>
    {/if}
  </section>
{/if}

<style>
  h2 {
    font-size: 1rem;
    color: #aaa;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    border-bottom: 1px solid #333;
    padding-bottom: 0.3rem;
    margin: 0;
  }

  .events-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.5rem;
  }

  .event-count {
    background: #333;
    color: #aaa;
    font-size: 0.75rem;
    padding: 0.1rem 0.5rem;
    border-radius: 10px;
    font-family: "SF Mono", "Fira Code", monospace;
  }

  .events-scroll {
    max-height: 350px;
    overflow-y: auto;
    border: 1px solid #2a2a3e;
    border-radius: 6px;
    background: #12122a;
    padding: 0.25rem 0;
  }

  .events-scroll::-webkit-scrollbar {
    width: 6px;
  }

  .events-scroll::-webkit-scrollbar-track {
    background: transparent;
  }

  .events-scroll::-webkit-scrollbar-thumb {
    background: #444;
    border-radius: 3px;
  }

  .events {
    position: relative;
  }

  .jump-bottom {
    position: absolute;
    bottom: 0.5rem;
    left: 50%;
    transform: translateX(-50%);
    padding: 0.3rem 1rem;
    font-size: 0.75rem;
    background: #e8d44d;
    color: #1a1a2e;
    border: none;
    border-radius: 12px;
    cursor: pointer;
    font-weight: 600;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.4);
    z-index: 1;
  }

  .jump-bottom:hover {
    background: #f0e060;
  }

  ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  .event {
    border-bottom: 1px solid #1e1e38;
  }

  .event:last-child {
    border-bottom: none;
  }

  .event-btn {
    display: flex;
    align-items: baseline;
    gap: 0.5rem;
    width: 100%;
    padding: 0.35rem 0.75rem;
    font-family: "SF Mono", "Fira Code", monospace;
    font-size: 0.85rem;
    background: none;
    border: none;
    color: inherit;
    cursor: pointer;
    text-align: left;
  }

  .event-emoji {
    flex-shrink: 0;
    font-size: 0.9rem;
    font-family:
      "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", sans-serif;
  }

  .event-text {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .event.expanded .event-btn .event-text {
    white-space: pre-wrap;
    overflow: visible;
    word-break: break-word;
  }

  .event-time {
    flex-shrink: 0;
    color: #555;
    font-size: 0.75rem;
  }

  .event.session_started {
    color: #4ecdc4;
  }

  .event.iteration_started {
    color: #888;
  }

  .event.tool_use {
    color: #a78bfa;
  }

  .event.assistant_text {
    color: #e0e0e0;
  }

  .event.iteration_complete {
    color: #34d399;
  }

  .event.session_complete {
    color: #e8d44d;
    font-weight: 600;
  }

  .event.check_started {
    color: #60a5fa;
  }

  .event.check_passed {
    color: #34d399;
  }

  .event.check_failed {
    color: #f87171;
  }

  .event.check_fix_started {
    color: #fbbf24;
  }

  .event.check_fix_complete {
    color: #a78bfa;
  }

  .event.git_sync_started {
    color: #888;
  }

  .event.git_sync_push_succeeded {
    color: #34d399;
  }

  .event.git_sync_conflict {
    color: #f59e0b;
  }

  .event.git_sync_conflict_resolve_started {
    color: #a78bfa;
  }

  .event.git_sync_conflict_resolve_complete {
    color: #34d399;
  }

  .event.git_sync_failed {
    color: #ef4444;
  }

  .tool-input-detail {
    margin: 0 0.75rem 0.5rem 2.2rem;
    padding: 0.5rem 0.75rem;
    background: #1a1a35;
    border: 1px solid #2a2a3e;
    border-radius: 4px;
    font-family: "SF Mono", "Fira Code", monospace;
    font-size: 0.78rem;
    color: #9ca3af;
    white-space: pre-wrap;
    word-break: break-word;
    overflow-x: auto;
  }
</style>

// src/components/EventsList.tsx
import { useState, useRef, useEffect, useMemo } from "react";
import type { SessionEvent } from "../types";
import { groupEventsByIteration } from "../iteration-groups";
import { eventEmoji, eventLabel } from "../event-format";
import { IterationGroupComponent } from "./IterationGroup";

interface EventsListProps {
  events: SessionEvent[];
  isLive?: boolean;
  repoPath?: string;
}

const eventKindColor: Record<string, string> = {
  session_started: "text-[#4ecdc4]",
  iteration_started: "text-[#888]",
  tool_use: "text-[#a78bfa]",
  assistant_text: "text-[#e0e0e0]",
  iteration_complete: "text-[#34d399]",
  session_complete: "text-[#e8d44d] font-semibold",
  check_started: "text-[#60a5fa]",
  check_passed: "text-[#34d399]",
  check_failed: "text-[#f87171]",
  check_fix_started: "text-[#fbbf24]",
  check_fix_complete: "text-[#a78bfa]",
  git_sync_started: "text-[#888]",
  git_sync_push_succeeded: "text-[#34d399]",
  git_sync_conflict: "text-[#f59e0b]",
  git_sync_conflict_resolve_started: "text-[#a78bfa]",
  git_sync_conflict_resolve_complete: "text-[#34d399]",
  git_sync_failed: "text-[#ef4444]",
};

export function EventsList({
  events,
  isLive = false,
  repoPath,
}: EventsListProps) {
  const [expandedEvents, setExpandedEvents] = useState<Set<number>>(new Set());
  const [expandedIterations, setExpandedIterations] = useState<Set<number>>(
    new Set(),
  );
  const [autoScroll, setAutoScroll] = useState(true);
  const lastExpandedIterRef = useRef(-1);
  const eventsContainerRef = useRef<HTMLDivElement>(null);

  const grouped = useMemo(() => groupEventsByIteration(events), [events]);

  // Compute global index mapping
  const { iterationGlobalStartIndices, afterStartIndex } = useMemo(() => {
    const map = new Map<number, number>();
    const beforeCount = grouped.standaloneEvents.filter(
      (s) => s.index === "before",
    ).length;
    let offset = beforeCount;
    for (const iter of grouped.iterations) {
      map.set(iter.iteration, offset);
      offset += iter.events.length;
    }
    return { iterationGlobalStartIndices: map, afterStartIndex: offset };
  }, [grouped]);

  // Auto-expand latest iteration when live
  useEffect(() => {
    if (isLive && grouped.iterations.length > 0) {
      const lastIter =
        grouped.iterations[grouped.iterations.length - 1].iteration;
      if (lastIter !== lastExpandedIterRef.current) {
        lastExpandedIterRef.current = lastIter;
        setExpandedIterations((prev) => {
          const next = new Set(prev);
          next.add(lastIter);
          return next;
        });
      }
    }
  }, [isLive, grouped.iterations]);

  // Auto-scroll on new events
  useEffect(() => {
    if (events.length > 0 && autoScroll) {
      requestAnimationFrame(() => {
        eventsContainerRef.current?.scrollTo({
          top: eventsContainerRef.current.scrollHeight,
          behavior: "smooth",
        });
      });
    }
  }, [events.length, autoScroll]);

  if (events.length === 0) return null;

  function toggleIteration(iteration: number) {
    setExpandedIterations((prev) => {
      const next = new Set(prev);
      if (next.has(iteration)) next.delete(iteration);
      else next.add(iteration);
      return next;
    });
  }

  function toggleEvent(globalIndex: number) {
    setExpandedEvents((prev) => {
      const next = new Set(prev);
      if (next.has(globalIndex)) next.delete(globalIndex);
      else next.add(globalIndex);
      return next;
    });
  }

  function formatTime(ts?: number): string {
    if (!ts) return "";
    const d = new Date(ts);
    return d.toLocaleTimeString([], {
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });
  }

  function handleEventsScroll() {
    const el = eventsContainerRef.current;
    if (!el) return;
    const { scrollTop, scrollHeight, clientHeight } = el;
    setAutoScroll(scrollHeight - scrollTop - clientHeight < 40);
  }

  function jumpToBottom() {
    eventsContainerRef.current?.scrollTo({
      top: eventsContainerRef.current.scrollHeight,
      behavior: "smooth",
    });
    setAutoScroll(true);
  }

  return (
    <section className="events relative">
      <div className="events-header flex items-center gap-2 mb-2">
        <h2 className="text-base text-[#aaa] uppercase tracking-wider border-b border-[#333] pb-1 m-0">
          Events
        </h2>
        <span className="event-count bg-[#333] text-[#aaa] text-xs px-2 py-0.5 rounded-[10px] font-mono">
          {events.length}
        </span>
      </div>
      <div
        ref={eventsContainerRef}
        className="events-scroll max-h-[350px] overflow-y-auto border border-[#2a2a3e] rounded-md bg-[#12122a] py-1"
        onScroll={handleEventsScroll}
      >
        <ul className="list-none p-0 m-0">
          {/* Before standalones */}
          {grouped.standaloneEvents
            .filter((s) => s.index === "before")
            .map((standalone, i) => {
              const isExpanded = expandedEvents.has(i);
              const colorClass = eventKindColor[standalone.event.kind] ?? "";
              return (
                <li
                  key={`before-${i}`}
                  className={`event ${standalone.event.kind}${isExpanded ? " expanded" : ""} ${colorClass} border-b border-[#1e1e38] last:border-b-0`}
                >
                  <button
                    className="event-btn flex items-baseline gap-2 w-full px-3 py-1 font-mono text-sm bg-transparent border-none text-inherit cursor-pointer text-left"
                    onClick={() => toggleEvent(i)}
                  >
                    <span className="event-emoji shrink-0">
                      {eventEmoji(standalone.event.kind)}
                    </span>
                    <span
                      className={`event-text flex-1 min-w-0 ${isExpanded ? "whitespace-pre-wrap break-words" : "overflow-hidden text-ellipsis whitespace-nowrap"}`}
                    >
                      {eventLabel(standalone.event, repoPath)}
                    </span>
                    <span className="event-time shrink-0 text-[#555] text-xs">
                      {formatTime(standalone.event._ts)}
                    </span>
                  </button>
                  {isExpanded &&
                    standalone.event.kind === "git_sync_failed" &&
                    standalone.event.error && (
                      <pre className="tool-input-detail mx-3 mb-2 ml-9 p-2 bg-[#1a1a35] border border-[#2a2a3e] rounded font-mono text-xs text-[#9ca3af] whitespace-pre-wrap break-words overflow-x-auto">
                        {standalone.event.error}
                      </pre>
                    )}
                </li>
              );
            })}

          {/* Iteration groups */}
          {grouped.iterations.map((iter) => (
            <IterationGroupComponent
              key={iter.iteration}
              group={iter}
              expanded={expandedIterations.has(iter.iteration)}
              onToggle={() => toggleIteration(iter.iteration)}
              formatTime={formatTime}
              expandedEvents={expandedEvents}
              toggleEvent={toggleEvent}
              globalStartIndex={
                iterationGlobalStartIndices.get(iter.iteration) ?? 0
              }
              repoPath={repoPath}
            />
          ))}

          {/* After standalones */}
          {grouped.standaloneEvents
            .filter((s) => s.index === "after")
            .map((standalone, i) => {
              const globalIndex = afterStartIndex + i;
              const isExpanded = expandedEvents.has(globalIndex);
              const colorClass = eventKindColor[standalone.event.kind] ?? "";
              return (
                <li
                  key={`after-${i}`}
                  className={`event ${standalone.event.kind}${isExpanded ? " expanded" : ""} ${colorClass} border-b border-[#1e1e38] last:border-b-0`}
                >
                  <button
                    className="event-btn flex items-baseline gap-2 w-full px-3 py-1 font-mono text-sm bg-transparent border-none text-inherit cursor-pointer text-left"
                    onClick={() => toggleEvent(globalIndex)}
                  >
                    <span className="event-emoji shrink-0">
                      {eventEmoji(standalone.event.kind)}
                    </span>
                    <span
                      className={`event-text flex-1 min-w-0 ${isExpanded ? "whitespace-pre-wrap break-words" : "overflow-hidden text-ellipsis whitespace-nowrap"}`}
                    >
                      {eventLabel(standalone.event, repoPath)}
                    </span>
                    <span className="event-time shrink-0 text-[#555] text-xs">
                      {formatTime(standalone.event._ts)}
                    </span>
                  </button>
                  {isExpanded &&
                    standalone.event.kind === "git_sync_failed" &&
                    standalone.event.error && (
                      <pre className="tool-input-detail mx-3 mb-2 ml-9 p-2 bg-[#1a1a35] border border-[#2a2a3e] rounded font-mono text-xs text-[#9ca3af] whitespace-pre-wrap break-words overflow-x-auto">
                        {standalone.event.error}
                      </pre>
                    )}
                </li>
              );
            })}
        </ul>
      </div>
      {!autoScroll && (
        <button
          className="jump-bottom absolute bottom-2 left-1/2 -translate-x-1/2 px-4 py-1 text-xs bg-[#e8d44d] text-[#1a1a2e] border-none rounded-xl cursor-pointer font-semibold shadow-md z-10 hover:bg-[#f0e060]"
          onClick={jumpToBottom}
        >
          ↓ New events
        </button>
      )}
    </section>
  );
}
